POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Tim Faust",
  "number": "123-456"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "123-456"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Tim Faust"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "040-123456"
}